### ISSUE TITLE
Add mentions of `wrangler dev` and `wrangler login` to "Getting started" page

### ISSUE THREAD

**Issue by davidtsong** [cloudflare/workers-docs-engine#201] opened 2020-08-26 17:05 UTC
It looks like there is some content for wrangler login but it still needs to be added to the quickstart guide. Wrangler dev isn't mentioned at all yet.

**Comment by adamschwartz** [comment] 2020-09-19 03:00
Closing as duplicate of https://github.com/cloudflare/workers-docs-engine/issues/197

**Closed by adamschwartz** 2020-09-19 03:00 UTC
Labels: content
